# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: flippi - Franco Lippi
email: franco@lippi.ar
description: >- # this means to ignore newlines until "baseurl:"
  👾 Dev. 💻 Tech enthusiast. 🎮 Casual gamer. 🚀 The life is that time while you deploy to production.
# Build settings
theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock |
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
plainwhite:
  name: Franco Lippi
  tagline: |
    <section style="text-align: center; display: block"><code>@flippi</code></section>
    <section style="text-align: center; display: block">👾 Dev. 🎮 Casual gamer.</section>
    <section style="text-align: center; display: block">💻 Tech enthusiast.</section>
    <section style="text-align: center; display: block">🎮 Casual gamer.</section>
  date_format: "%b %-d, %Y"
  portfolio_image:  "assets/profile.png" # the path from the base directory of the site to the image to display (no / at the start)
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  sitemap: true # set to true to generate sitemap.xml content
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp

  social_links:
    twitter: flippiJS
    github: flippiJS
    linkedIn: in/franco-lippi-885a99147 # format: locale/username
